def guided_gradcam(cam, gb):
    '''

    :param cam: heatmap generated by GradCAM
    :param gb: gradients calculated by Guided-Backpropagation
    :return: the element-wise multiplication of cam and gb
    '''

    guided_gradcam = gb*cam

    return guided_gradcam